# Generated by Django 3.2.2 on 2021-05-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='enter_the_amount_to_be_transferred_in_INR',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='enter_the_destination_account_number',
            new_name='transfer',
        ),
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='enter_your_user_name',
            new_name='your_username',
        ),
    ]
