# Generated by Django 3.2.2 on 2021-05-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210508_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='account_number',
            new_name='account_number_transfer',
        ),
    ]
