# Generated by Django 3.2.2 on 2021-05-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210508_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='enter_the_amount_to_be_transferred_in_INR',
            new_name='enter_the_amount_to_be_transferred_in_USD',
        ),
        migrations.AlterField(
            model_name='presentlocation',
            name='country',
            field=models.CharField(default='Indonesia', max_length=50),
        ),
    ]
