# Generated by Django 3.2.2 on 2021-05-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210509_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('address', models.CharField(default=None, max_length=50)),
                ('phone', models.IntegerField(default=0, max_length=20)),
                ('user_name', models.CharField(default=None, max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='BasicDetails',
        ),
    ]
