# Generated by Django 3.2.2 on 2021-05-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='enter_your_user_name',
            new_name='Masukan_Nama_Penyetor',
        ),
    ]
