# Generated by Django 3.2.2 on 2021-05-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_rename_enter_your_user_name_moneytransfer_masukan_nama_penyetor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='enter_the_destination_account_number',
            new_name='Masukan_No_Akuns_Tujuan',
        ),
    ]
