# Generated by Django 3.2.2 on 2021-05-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_rename_enter_the_destination_account_number_moneytransfer_masukan_no_akuns_tujuan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='enter_the_amount_to_be_transferred_in_USD',
            new_name='Masukan_Jumlah_Uang_Dalam_USD',
        ),
    ]
