# Generated by Django 3.2.2 on 2021-05-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_rename_enter_the_amount_to_be_transferred_in_usd_moneytransfer_masukan_jumlah_uang_dalam_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='account_number',
            field=models.IntegerField(default=0),
        ),
    ]
