# Generated by Django 3.2.2 on 2021-05-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_status_account_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PresentLocation',
        ),
    ]
