# Generated by Django 3.2.2 on 2021-05-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akuns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='addres',
            new_name='address',
        ),
    ]
