# Generated by Django 3.2.2 on 2021-05-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akuns', '0002_rename_addres_user_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
