# Generated by Django 3.2.2 on 2021-05-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akuns', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
